spring.profiles.include=@profileActive@

server.servlet.context-path=/operationstool
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

jwt.secretKey=xOhjZcn2R8aDy/8yU9pJaZSt0N3FKQ+Lb7viSEOiXts=
commonsapp.url=https://localapps.imcd.es/commonApps/index.html
