
## do we need this - confirm con enrique?
saml.entityIdIDP=https://idp.eu.safenetid.com/auth/realms/3Y5F2GQD1V-STA
saml.entityIdSP=https://localapps.imcd.es/CommonApps/Safenet
saml.ssoUrl=https://idp.eu.safenetid.com/auth/realms/3Y5F2GQD1V-STA/protocol/saml
saml.sloUrl=https://idp.eu.safenetid.com/auth/realms/3Y5F2GQD1V-STA/protocol/saml
saml.consumerServiceLocation=https://localapps.imcd.es/commonApps/saml/acs
aws.datasource.secret=pro/JavaApps

## which port to use?
server.port=8084